blacklisted-names = ["foo", "bar", "baz", "quux"] # clippy::blacklisted_name
cognitive-complexity-threshold = 25               # clippy::cognitive_complexity
doc-valid-idents = ["KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "DirectX", "ECMAScript", "GPLv2", "GPLv3", "GitHub", "GitLab", "IPv4", "IPv6", "JavaScript", "NaN", "NaNs", "OAuth", "OpenGL", "OpenSSH", "OpenSSL", "OpenStreetMap", "TrueType", "iOS", "macOS", "TeX", "LaTeX", "BibTeX", "BibLaTeX", "MinGW", "CamelCase"] # clippy::doc_markdown
enum-variant-name-threshold = 3                   # clippy::enum_variant_names
enum-variant-size-threshold = 200                 # clippy::large_enum_variant
single-char-binding-names-threshold = 5           # clippy::many_single_char_names
too-large-for-stack = 200                         # clippy::boxed_local
too-many-arguments-threshold = 7                  # clippy::too_many_arguments
trivial-copy-size-limit = 1                       # clippy::trivially_copy_pass_by_ref
type-complexity-threshold = 250                   # clippy::type_complexity
verbose-bit-mask-threshold = 1                    # clippy::verbose_bit_mask
# too_many_lines = 100                            # clippy::too_many_lines