# 1: Build the builder images
FROM rust:latest as builder
ENV PKG_CONFIG_ALLOW_CROSS=1
WORKDIR /usr/src
# 1a: Install dependencies
RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y pkg-config libssl-dev && \
    # musl-tools && \
    rustup target add aarch64-unknown-linux-musl